# Generated by Django 2.0.7 on 2018-08-07 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, null=True, verbose_name='location')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='phone')),
                ('things_i_love', models.TextField(max_length=200, null=True, verbose_name='things_i_love')),
                ('joined_date', models.DateTimeField(null=True, verbose_name='joined_date')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='user_profile/', verbose_name='profile_picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User profile',
            },
        ),
    ]

