# Generated by Django 2.0.7 on 2018-08-14 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='things_i_love',
        ),
    ]
