version: '3'
services:
  app:
    image: "${CI_PIPELINE_ID}:${CI_COMMIT_REF_NAME}"
    env_file:
      - dev.env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: user01
      POSTGRES_DATABASE: postgres
