name: app
channels:
- conda-forge
dependencies:
  - python=3.6
  - psycopg2==2.7.5
  - pip:
    - django==2.0.7
    - flake8
    - djangorestframework==3.8.2
    - djangorestframework-simplejwt==3.2.3
    - coreapi==2.3.3
    - Pillow==5.2.0
    - django-cors-headers