# Generated by Django 2.0.7 on 2018-08-14 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('category', models.CharField(choices=[('restaurant', 'Restaurant'), ('fast_food', 'Fast_Food'), ('cafe', 'Cafe')], max_length=100, verbose_name='category')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='country')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='street')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='city')),
                ('ZIP', models.CharField(blank=True, default='0000', max_length=10, verbose_name='ZIP')),
                ('website', models.CharField(blank=True, max_length=100, null=True, verbose_name='website')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
                ('opening_hours', models.DateTimeField(null=True, verbose_name='opening_hours')),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant/', verbose_name='restaurant picture')),
                ('credit_card', models.NullBooleanField(verbose_name='credit_card')),
                ('take_reservation', models.NullBooleanField(verbose_name='take_reservation')),
                ('kids_menu', models.NullBooleanField(verbose_name='kids_menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
