# Generated by Django 2.0.7 on 2018-08-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='credit_card',
            field=models.NullBooleanField(default=False, verbose_name='credit_card'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='kids_menu',
            field=models.NullBooleanField(default=False, verbose_name='kids_menu'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='take_reservation',
            field=models.NullBooleanField(default=False, verbose_name='take_reservation'),
        ),
    ]
