# Generated by Django 2.0.7 on 2018-08-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20180816_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='opening_hours',
            field=models.TextField(null=True, verbose_name='opening_hours'),
        ),
    ]
