# Generated by Django 2.0.7 on 2018-08-14 14:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, verbose_name='content')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='rating')),
                ('date_created', models.DateTimeField(null=True, verbose_name='date_created')),
                ('date_modified', models.DateTimeField(null=True, verbose_name='date_modified')),
                ('friendly_waiting_staff', models.NullBooleanField(verbose_name='friendly_waiting_staff')),
                ('high_chair', models.NullBooleanField(verbose_name='high_chair')),
                ('are_there_steps', models.NullBooleanField(verbose_name='are_there_steps')),
                ('has_tablecloth', models.NullBooleanField(verbose_name='has_tablecloth')),
                ('has_quick_service', models.NullBooleanField(verbose_name='has_quick_service')),
                ('price_level', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)], verbose_name='price_level')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurant.Restaurant', verbose_name='restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
