# Generated by Django 2.0.7 on 2018-08-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='has_changing_table',
            field=models.NullBooleanField(verbose_name='has_changing_table'),
        ),
        migrations.AddField(
            model_name='review',
            name='isNoisy',
            field=models.NullBooleanField(verbose_name='isNoisy'),
        ),
        migrations.AddField(
            model_name='review',
            name='place_for_stroller',
            field=models.NullBooleanField(verbose_name='place_for_stroller'),
        ),
    ]
